@route = http://localhost:3000/seccion

### get tasks
GET {{route}}

### create task
POST {{route}}
Content-Type: application/json

{
    "IDPadre": null, 
    "IDTemplate": 1,
    "Nombre": "hardware" , 
    "Min": 0, 
    "Max": 2
}

### get task
GET {{route}}/1

### delete task
DELETE {{route}}/1

### update task
PUT {{route}}/3
Content-Type: application/json

{  
    "IDPadre": 2, 
    "IDTemplate": 1,
    "Nombre": "software",
    "Min": 1, 
    "Max": 2    
}